version: '3.1'
#
# sudo docker-compose up -d
# sudo docker-compose start
# sudo docker-compose ps
# sudo docker exec -it dkcomposer_samba /bin/bash
# sudo docker-compose stop
# sudo docker-compose down
#
services:
  transmission:
    container_name: dkcomposer_transmission
    build: ./transmission
    ports:
      - 9991:9091
      - 9992:51413
    volumes:
      - ./volumes_transmission_config:/config
      - ./volumes_transmission_downloads:/downloads
      - ./volumes_transmission_watch:/watch
  sambaserver:
    container_name: dkcomposer_samba
    build: ./sambaserver
    stdin_open: true # -i option
    tty: true # -t option
    # entrypoint: ["service", "smbd", "restart"]
    ports:
      - 9993:193
      - 9994:445
    volumes:
      - ./volumes_transmission_downloads/complete:/sharedsmb
    command: bash -c "service smbd restart && /bin/sh"
